version: "3"

services:
  main:
    image: serif-take-home:latest
    build:
      context: ..
      dockerfile: .docker/go.Dockerfile
    working_dir: /serif-take-home
    command: go run /serif-take-home/main.go
    volumes:
      - ..:/serif-take-home
